### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by guilllaumeB** [javiljoen/lttb.py#2]
Hi.

Some time is spent to perform the test:
```
    if any(data[:, 0] != np.sort(data[:, 0])):
        raise ValueError('data should be sorted on first column')
```

i think you could replace this by:
```
    if np.any(np.diff(data[:, 0])<=0):
        raise ValueError('data should be sorted on first column')
```

that allows to speedup this test by a factor 2

**Comment by guilllaumeB** [comment]
More efficient (again):
```
    if np.any(data[1:, 0]<=data[:-1, 0]):
        raise ValueError('data should be sorted on first column')
```

**Comment by javiljoen** [comment]
Thanks for the suggestions, @guilllaumeB. That is a much better way of doing the check :)

I've implemented these in v. 0.2.0, and added you to the contributor list in the Readme.

**Comment by ardzoht** [comment]
Shouldn't the check be` np.any(data[1:, 0]<data[:-1, 0])`? I'm getting the ValueError raise being that consecutive values in a sorted array are equal.

**Comment by guilllaumeB** [comment]
@ardzoht 
To my mind, a time series implies that abscissas are strictly growing. Then a vector with equal values is not a valid abscissas vector.
But maybe I'm wrong, time series are not my field of expertise, I used to work with analog signals, that implies strictly growing abscissas
