### ISSUE TITLE
python2: invalid encoding of setup.py

### ISSUE THREAD

**Issue by birkenfeld** [javiljoen/lttb.py#5]
It's not clear to me if python2 is still supposed to be supported (it's in tox.ini at least), but with 0.2.1 from PyPI I get:

$ python2 setup.py
   File "setup.py", line 9
SyntaxError: Non-ASCII character '\xe2' in file setup.py on line 9, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by javiljoen** [comment]
Thanks for the report, @birkenfeld.
I think this has been fixed in PR #6; you should be able to install v. 0.2.2 from PyPI.
Please let me know if you run into any other issues with Python 2.
